name: 0.6.0
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        wget --quiet --output-document=- https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz | tar Jx
        mv zig-linux-x86_64-* zig
        echo zig version $(./zig/zig version)
    - name: test
      run: |
        ./zig/zig build test

