name: master
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        ZIG=$(wget --quiet --output-document=- https://ziglang.org/download/index.json | jq --raw-output '.master."x86_64-linux".tarball')
        wget --quiet --output-document=- $ZIG | tar Jx
        mv zig-linux-x86_64-* zig
        echo zig version $(./zig/zig version)
    - name: test
      run: |
        ./zig/zig build test

