name: stable
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        wget --quiet --output-document=- https://ziglang.org/download/0.8.1/zig-linux-x86_64-0.8.1.tar.xz | tar Jx
        mv zig-linux-x86_64-* zig
        echo zig version $(./zig/zig version)
    - name: build
      run: |        
        ./zig/zig build
        ./zig-out/bin/zigjvm test/Add.class
    - name: test
      run: |
        ./zig/zig build test
